 repos:
   - repo: https://github.com/PyCQA/flake8
     rev: 7.0.0
     hooks:
     - id: flake8
       args: [--max-line-length=79, inline-quotes = "]

   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v1.11.2
     hooks:
       - id: mypy
         exclude: ^(docs/|example-plugin/)