name: check

on:
  push:
    branches:
      - 'devops'



jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: run flake8
      run: |
        python -m flake8 --config-toml=./project.toml
